[build]
  command = "hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.23.2"
  TZ = "GMT+1"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.135.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.135.0"